# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oktsec < Formula
  desc "Runtime security for AI agents. Intercepts tool calls, scans with 268 rules, tamper-evident audit trail."
  homepage "https://oktsec.com"
  version "0.15.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oktsec/oktsec/releases/download/v0.15.2/oktsec_0.15.2_darwin_amd64.tar.gz"
      sha256 "8ae5bfee7aaf369d476ea2abc5912241fde40ce5ea302f9cd1fc80040893d5ec"

      define_method(:install) do
        bin.install "oktsec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oktsec/oktsec/releases/download/v0.15.2/oktsec_0.15.2_darwin_arm64.tar.gz"
      sha256 "b5491feebb79b80492b7c5a35dba1196791519af046e9c367554e5ad4caa59e2"

      define_method(:install) do
        bin.install "oktsec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oktsec/oktsec/releases/download/v0.15.2/oktsec_0.15.2_linux_amd64.tar.gz"
      sha256 "e0a373a987072503d364288e3d1c8ab3476a59c52b14a13cfed6545236c7c93e"
      define_method(:install) do
        bin.install "oktsec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oktsec/oktsec/releases/download/v0.15.2/oktsec_0.15.2_linux_arm64.tar.gz"
      sha256 "635b63bd075f7ce3b01c5e27d98d5e0f4c6e1e1818d469905401cca8020afbd0"
      define_method(:install) do
        bin.install "oktsec"
      end
    end
  end

  test do
    system "#{bin}/oktsec", "version"
  end
end
